"use strict";

//Anything under 1000 reserved due to HTTP status codes
module.exports = {
  "-1": "Unknown",
  "403": "Operation/Request is forbidden.",
  "404": "Not Found.",
  "666": "Route not found.",
  "1000": "invoice status must be an integer.",
  "1001":
    "invoice status is invalid.  Must be either 0 for open or 2 for closed.",
  "1003":
    "account status is invalid.  Must be either NEW, ACTIVE, SUSPENDED or CLOSED.",
  "1004": "account status must be one of 'ACTIVE', 'SUSPENDED' or 'CLOSED'.",
  "1005": "language must be 2 chars long.",
  "1006": "language must be either 'EN' or 'FR'.",
  "1007": "New status is equal to current status.",
  "1008": "name cannot be empty.",
  "1009": "fname cannot be empty.",
  "1010": "lname cannot be empty.",
  "1011": "address1 cannot be empty.",
  "1012": "address2 cannot be empty.",
  "1013": "address3 cannot be empty.",
  "1014": "city cannot be empty.",
  "1015": "province must be 2 chars long.",
  "1016": "country must be 2 chars long.",
  "1017": "Invalid postalCode format.  Should be: A1A 1A1 or A1A1A1.",
  "1018": "Invalid emailAddress.",
  "1019": "billParentAccount flag must be a boolean: true or false.",
  "1020":
    "recurringCharge must be a number greater than 0 and with a maximum of 2 decimal places.",
  "1021": "planCode is required.",
  "1022":
    "telephoneNumber is not valid. Must have length 11, begin with a '1' and both the exchange/area code cannot start with a 1 or 0.",
  "1023": "telephoneNumber is required.",
  "1024": "sim must be between 19 and 20 chars long.",
  "1025": "sim is required.",
  "1026": "imei must be between 15 and 17 chars long.",
  "1027": "imei is required.",
  "1028": "fname is required.",
  "1029": "lname is required.",
  "1030": "address1 is required.",
  "1031": "city is required.",
  "1032": "province is required.",
  "1033": "country is required.",
  "1034": "postalCode is required.",
  "1035": "emailAddress is required.",
  "1036": "agentId cannot be empty.",
  "1037": "planCode cannot be empty.",
  "1038":
    "status must be a comma-delimited string with values NEW, ACTIVE, SUSPENDED, and/or CLOSED.",
  "1039": "The specified plan code is not available for this account.",
  "1040": "Cannot bill to non-active parent account.",
  "1041":
    "Cannot set status of a service account if the parent account is not active ('NEW', 'ACTIVE' or 'SUSPENDED').",
  "1042": "The specified plan code is not available for this account.",
  "1043": "Cannot change plan due to different billing types.",
  "1044": "status should only appear once in query.",
  "1045": "query should only appear once in query.",
  "1046": "phone should be an object.",
  "1047": "home should be a string or null.",
  "1048": "business should be a string or null.",
  "1049": "mobile should be a string or null.",
  "1050": "commissionCode cannot be empty.",
  "1051": "agentId AND commissionCode are required.",
  "1052": "contract length cannot be empty.",
  "1053": "contract length must be at least 1.",
  "1054": "contract length is required.",
  "1055": "startDate is invalid. Must be in format YYYY-MM-DD.",
  "1056": "startDate must be equal or greater then today.",
  "1057": "pin must be 4 chars long.",
  "1058": "pin must be a number.",
  "1059": "enabled must be a boolean:  true/false.",
  "1060": "enabled is required.",
  "1061": "voicemail feature is not supported on this plan for this account.",
  "1062":
    "call forwarding feature is not supported on this plan for this account.",
  "1063":
    "forwardToNumber is not valid. Must have length 11 and start with a '1'.",
  "1064": "forwardToNumber is required.",
  "1065": "numberOfRings must be at least 1.",
  "1066": "page must be an integer greater than 0.",
  "1067": "pageLimit must be an integer greater than 0.",
  "2001": "fromDate is invalid. Must be in format YYYY-MM-DD.",
  "2002": "toDate is invalid. Must be in format YYYY-MM-DD.",
  "2003": "reference cannot be empty.",
  "2004": "note is required.",
  "2005": "Credit card type must be one of 'VISA', 'MASTERCARD' or 'AMEX'.",
  "2006": "Credit card type is required.",
  "2007": "The Credit Card number must be between 15 and 16 chars long.",
  "2008": "The Credit Card number is not valid.",
  "2009": "The Credit Card number is required.",
  "2010": "Credit card holder is required.",
  "2011": "The Credit Card Expiry Month must be 2 chars long.",
  "2012": "The Credit Card Expiry Month is invalid.",
  "2013": "The Credit Card Expiry Month is required.",
  "2014": "The Credit Card Expiry Year must be 4 chars long.",
  "2015": "The Credit Card Expiry Year is invalid.",
  "2016": "The Credit Card Expiry Year is required.",
  "2017": "The Credit Card CVV is invalid.",
  "2018": "The Credit Card CVV is required.",
  "2019": "enabled flag must be a boolean: true or false.",
  "2020": "enabled flag is required.",
  "2021": "onDeclineSuspend flag must be a boolean: true or false.",
  "2022": "paymentSource must be one of 'CREDITCARD' or 'BANKACCOUNT'.",
  "2023": "paymentSource is required.",
  "2024": "onDaysAvailable enabled flag must be a boolean: true or false.",
  "2025": "onDaysAvailable enabled flag is required.",
  "2026": "onDaysAvailable trigger must be greater than 1 and an integer.",
  "2027": "onDaysAvailable trigger is required.",
  "2028":
    "onDaysAvailable amount must be greater than or equal to 1 and with a maximum of 2 decimal places.",
  "2029": "onDaysAvailable amount is required.",
  "2030": "onDayOfMonth enabled flag must be a boolean: true or false.",
  "2031": "onDayOfMonth enabled flag is required.",
  "2032":
    "onDayOfMonth trigger must be greater than 1 and less than 28 and an integer.",
  "2033": "onDayOfMonth trigger is required.",
  "2034":
    "onDayOfMonth amount must be greater than or equal to 1 and with a maximum of 2 decimal places.",
  "2035": "onDayOfMonth amount is required.",
  "2036": "onBalanceBelow enabled flag must be a boolean: true or false.",
  "2037": "onBalanceBelow enabled flag is required.",
  "2038":
    "onBalanceBelow trigger must be greater than or equal to 1 and an integer.",
  "2039": "onBalanceBelow trigger is required.",
  "2040":
    "onBalanceBelow amount must be greater than or equal to 1 and with a maximum of 2 decimal places.",
  "2041": "onBalanceBelow amount is required.",
  "2042": "type must be 'SECDEPOSIT'.",
  "2043": "type is required.",
  "2044": "currency must be either 'CAD' or 'USD'.",
  "2045": "currency is required.",
  "2046": "amount must be a valid positive number.",
  "2047": "amount is required.",
  "2048": "note cannot be empty.",
  "2049": "adjustments must be an array.",
  "2050": "adjustments length must be at least 1.",
  "2051": "amount must be a number.",
  "2052":
    "paymentMethod must be one of CASH, CHEQUE, CREDITCARD, DEBITCARD, WIRE, ACH, PAYPAL or VOUCHER.",
  "2053": "paymentMethod is required.",
  "2054": "reference cannot be empty.",
  "2055": "type must be one of 'BALANCEMIGR', 'CRED', 'DEP', 'EC' or 'MISC'",
  "2056": "paymentSource must be specified.",
  "2057":
    "For a postpaid account, 'onDaysAvailable', 'onDayOfMonth' and/or 'onBalanceBelow' are not allowed.",
  "2058":
    "For a prepaid account, Automatic Payment must have at least one of 'onDaysAvailable', 'onDayOfMonth' and/or 'onBalanceBelow' configured.",
  "2059": "Invalid payment source for business unit.",
  "2060": "fromDate must come before toDate.",
  "2061": "Invalid fromDate.",
  "2062": "Invalid toDate.",
  "2063":
    "Status must be a comma-delimited string with values 'OPEN', 'PAIN', 'RETURNED', and/or 'DELETED'.",
  "2064": "adjustments is required and cannot be empty.",
  "2065": "fromDate should only appear once in query.",
  "2066": "toDate should only appear once in query.",
  "2067": "reference should only appear once in query.",
  "2068": "paymentId should only appear once in query.",
  "2069": "refundId should only appear once in query.",
  "2070": "type should only appear once in query.",
  "2071": "productCode should only appear once in query.",
  "2072": "Both fromDate and toDate must be specified in query.",
  "2073": "Credit Card update is not allowed on non billable accounts.",
  "2074": "invoiceId cannot be empty.",
  "2075": "date cannot be empty.",
  "2076": "type is required.",
  "2077":
    "type must be one of 'ASDL', 'GPRS', 'FAX', 'MOBILEINC', 'MOBILEOUT', 'RGPRS', 'RMOBILEINC', 'RMOBILEOUT', RSMSINC', RSMSOUT', 'SMSINC', 'SMSOUT' or 'VOIP'.",
  "2078": "invoiceId not supported for a prepaid account.",
  "2079": "date is invalid. Must be in format YYYY-MM.",
  "2080": "isServicePayment enabled flag must be a boolean: true or false.",
  "2081":
    "Automatic payments not supported for billParentAccount=true services.",
  "2082": "Package list available only on master accounts.",
  "2083": "Add package available only on master accounts.",
  "2084": "Delete package available only on master accounts.",
  "3000": "areaCode must be 3 chars long.",
  "3001": "The areaCode is invalid.",
  "3002": "areaCode is required.",
  "3003": "exchangeCode must be 3 chars long.",
  "3004": "The exchangeCode is invalid.",
  "3005": "exchangeCode is required.",
  "3006": "serviceId cannot be empty.",
  "3007": "accountId cannot be empty.",
  "3008":
    "telephoneNumber is not valid. Must have length 11 and start with a '1'.",
  "3009": "telephoneNumber cannot be empty.",
  "3010": "requestDate is not valid. Must be in format YYYY-MM-DD.",
  "3011": "requestDate cannot be empty.",
  "3012": "desiredDueDate is not valid. Must be in format YYYY-MM-DD.",
  "3013": "desiredDueDate cannot be empty.",
  "3014": "providerName cannot be empty.",
  "3015": "providerAccountNumber cannot be empty.",
  "3016": "serviceType is not valid. Must be either wireless or wireline.",
  "3017": "serviceType cannot be empty.",
  "3018": "fullName cannot be empty.",
  "3019": "streetNumber cannot be empty.",
  "3020": "streetName must contain only letters and/or numbers and spaces.",
  "3021": "streetName cannot be empty.",
  "3022": "unitNumber must contain only letters and/or numbers.",
  "3023": "telephoneNumber is required.",
  "3024": "providerName is required.",
  "3025": "providerAccountNumber is required.",
  "3026": "desiredDueDate is required.",
  "3027": "serviceType is required.",
  "3028": "fullName is required.",
  "3029": "streetNumber is required.",
  "3030": "streetName is required.",
  "3031": "city is required.",
  "3032": "serviceId is required.",
  "3033": "comments cannot be empty.",
  "3034": "serviceId should only appear once in query.",
  "3035": "accountId should only appear once in query.",
  "3036": "telephoneNumber should only appear once in query.",
  "3037": "requestDate should only appear once in query.",
  "3038": "desiredDueDate should only appear once in query.",
  "3039": "city can only contain alphanumeric characters including space.",
  "3040":
    "providerName can only contain alphanumeric characters including space.",
  "4000": "iccid cannot be empty.",
  "4001": "imsi cannot be empty.",
  "4002": "puk cannot be empty.",
  "4003": "iccid should only appear once in query.",
  "4004": "imsi should only appear once in query.",
  "4005": "puk should only appear once in query.",
  "4006": "udf1 should only appear once in query.",
  "4007": "udf2 should only appear once in query.",
  "4008": "udf3 should only appear once in query.",
  "5000": "lineNumber must be 4 chars long.",
  "5001": "The lineNumber is invalid.",
  "5002": "fullNumber must be 11 chars long.",
  "5003": "The fullNumber is invalid.",
  "5004": "inUse flag must be a boolean: true or false.",
  "5005": "telephoneNumbers must be an array.",
  "5006": "telephoneNumbers length must be at least 1.",
  "5007": "One or more telephone number is invalid.",
  "5008": "telephoneNumbers is required.",
  "5009": "country should only appear once in query.",
  "5010": "city should only appear once in query.",
  "5011": "province should only appear once in query.",
  "5012": "areaCode should only appear once in query.",
  "5013": "exchangeCode should only appear once in query.",
  "5014": "lineNumber should only appear once in query.",
  "5015": "fullNumber should only appear once in query.",
  "5016": "inUse should only appear once in query.",
  "5017": "checkLastUsed flag must be a boolean: true or false.",
  "5018": "checkLastUsed should only appear once in query.",
  "5019": "lastUsed is not valid. Must be in format YYYY-MM-DD.",
  "5020": "lastUsed cannot be empty.",
  "5020": "lat is not a valid geocode.",
  "5021": "lat cannot be empty.",
  "5022": "lng is not a valid geocode.",
  "5023": "lng cannot be empty.",
  "5024": "lat/lng are both required.",
  "6000": "enabled must be a boolean: true or false.",
  "6001": "url is invalid. Must start with http or https.",
  "6002": "url is required.",
  "6003": "token is required.",
  "6004": "header is required.",
  "6005": "event is required.",
  "6006": "target_url is invalid. Must start with https.",
  "6007": "target_url is required.",
  "6008": "One of target_url and/or event is required.",
  "6009": "target_url cannot be empty.",
  "6010": "event cannot be empty.",
  "7000": "planCode is required.",
  "7001": "billingType is required.",
  "7002": "billingType must be either 'postpaid' or 'prepaid'.",
  "7003": "recurringCharge is required.",
  "7004": "recurringCharge must be an integer.",
  "7005": "billable is required.",
  "7006": "billable must be a boolean: true or false.",
  "7007": "active must be a boolean: true or false.",
  "7008": "flatRateTariff is required.",
  "7009": "planType is required.",
  "7010": "allotment must be a valid json.",
  "7011": "broadsoft must be a valid json.",
  "7012": "ipswitch must be a valid json.",
  "7013": "huawei must be a valid json.",
  "7014": "nextologies must be a valid json.",
  "7015": "flatRateTariff must be not empty string.",
  "7016": "planType must be not empty string.",
  "7017": "Update Plan failed due to invalid permission or does not exist.",
  "7018": "Delete Plan failed due to invalid permission or does not exist.",
  "7019": "You may not delete this plan since it is linked to one or more services",
  "10000": "The specified serviceId cannot be found.",
  "10001":
    "Updates to a non-active ('NEW', 'ACTIVE', or 'SUSPENDED') account are forbidden.",
  "10002": "Please unassign the telephone number assigned to this account.",
  "10003": "Please unassign the sim assigned to this account.",
  "10004":
    "Cannot bill to parent account because existing current service plan is billable.",
  "10005":
    "Cannot add/change imei of a non-active ('NEW', 'ACTIVE' or 'SUSPENDED') account.",
  "10006":
    "Cannot add/change sim from a non ('NEW', 'ACTIVE', 'CLOSED' or 'SUSPENDED') account.",
  "10007":
    "Cannot add/change telephone number from a non ('NEW', 'ACTIVE', 'CLOSED' or 'SUSPENDED') account.",
  "10008": "The requested telephone number is no longer available.",
  "10009": "Cannot update plan of a non-active ('ACTIVE') service account.",
  "10010": "New plan code is the same as the current plan code.",
  "10011":
    "Request may not be cancelled if status is confirmed and due date is < 24 hours from now.",
  "10012":
    "The specified requestId is already Closed, Canceled, Pending Cancellation or does not exist.",
  "10013":
    "The specified requestId is not in a valid state to be updated or does not exist.",
  "10014":
    "The specified desiredDueDate must be greater than 3 days from the current date.",
  "10015":
    "No updates can be performed on this porting request since it has been confirmed and the due date is less than or equal to 1 day from the current date.",
  "10016":
    "The specified desiredDueDate must be greater than 3 days from the current date for a Wireline service.",
  "10017":
    "The specified desiredDueDate must be greater than 1 days from the current date for a Wireless service.",
  "10018": "The specified serviceId already has an open porting request.",
  "10019": "The specified serviceId does not exist.",
  "10020": "An account with that ID cannot be found.",
  "10021": "SIM Card not found.",
  "10022": "Get Invoice failed due to: Invoice not found.",
  "10023": "Get Adjustment failed due to: Adjustment Id not found for account.",
  "10024": "Get Deposit failed due to: Deposit Id not found for account.",
  "10025": "Invalid Authorization header.",
  "10026": "Unable to verify API Key.",
  "10027": "Invalid API key.",
  "10028": "Authorization or Iristelx-Api-Key header required.",
  "10029": "Get Plan failed due to: Plan not found.",
  "10030":
    "This number can't be ported right now because it is already in an open porting request.",
  "10031":
    "You must provide a comment when updating the desired due date of a non-confirmed porting request.",
  "10032":
    "You are only allowed to change the desired due date on a confirmed porting request. Please delete all other parameters.",
  "10033": "Telephone number change not allowed for legacy service.",
  "10034": "Get Payment failed due to: Payemnt Id not found for account.",
  "10035": "SIM change not allowed for legacy service.",
  "10036": "Telephone number delete not allowed for legacy model.",
  "10037":
    "Account status must be either ('NEW', 'ACTIVE', or 'SUSPENDED') to add/delete packages.",
  "10038": "Package code is required.",
  "10039": "Delete Issue failed due to does not exist."
};
